[project]
name = "integrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pulumi>=3.133.0",
    "pulumi-aws>=6.52.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.7",
]
